### ISSUE TITLE
Saving note causes freeze for 10-60 seconds depending on the imported pdf's size.

### ISSUE THREAD

**Issue by atahanacar** [saber-notes/saber#1189]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

When saving a note, the entire app becomes unresponsive until saving is completed.

### To reproduce

1. Open a note
2. Import pdf
3. Write/use the note normally
4. Save/autosave
5. Experience a complete freeze of the App for 10-60 seconds (proportional to pdf's filesize)

### Expected behavior

The app shouldn't freeze.

### Saber version

v0.21.2 F-Droid (21020)

### Device

- Device: Samsung Galaxy Tab S6 Lite
- OS: Android 13 (LineageOS)

### Anything else?

v0.21.1 doesn't have this issue.

**Comment by atahanacar** [comment]
Happens on any pdf I tried, ranging from 400 KB to 15 MB. Pages range from 15 to 200. Unfortunately, I'm not allowed to share them as they contain sensitive information about other people, but they are all different pdfs from different sources, some from Libreoffice, some from powerpoint etc.

I've also checked the logcat, nothing related there.

**Comment by trashyms** [comment]
Happening with any pdf size.

**Comment by atahanacar** [comment]
Just tested it, also happens on Linux flatpak v0.21.2

**Comment by QubaB** [comment]
I think that the problem is that during saving note is saved pdf itself. Behavior should be probably changed to not save the pdf itself but only handwriting. This will increase the speed of saving. 

It needs to rewrite AssetsCache and Save code. I will try to implement it, but it will be quite a big change.

**Comment by atahanacar** [comment]
After fiddling around with the flutter profiler, I found out that OrderedAssetCache.add method is the culprit after commit a95f44b.

**Comment by QubaB** [comment]
> After fiddling around with the flutter profiler, I found out that OrderedAssetCache.add method is the culprit after commit [a95f44b](https://github.com/saber-notes/saber/commit/a95f44bb2d275d57cabb42f3779bd13019cbf725).

You are right @atahanacar. Code inserted in commit https://github.com/saber-notes/saber/commit/a95f44bb2d275d57cabb42f3779bd13019cbf725 causes slow saving of note. It should be improved. This part of code (suggested by me) avoided saving notes with missing pdf pages, but causes another problem. 

We should switch to different type of comparison of assets - not byte per byte.  Thank you for pointing on this commit.

**Comment by atahanacar** [comment]
I am working on caching the OrderedAssetCache index of the pdf file in AssetCache using the pdfs file path. This should solve the issue of comparing entire pdf byte by byte for every single page.

**Comment by QubaB** [comment]
Comparison of pdf file byte by byte was implemented because code `index = _cache.indexOf(value);`  sometimes returns index -1 (it means that the sequence of bytes is not the same as already cached) even if the sequence was already in cache. And it caused problem with disapearing pdf pages. So I added this additional comparison byte by byte to avoid this problem of function indexOf.

**Comment by atahanacar** [comment]
For this reason, I'm adding another check that if a pdf file with the same path is passed to `OrderedAssetCache.add` twice, it will load the index from a newly added cache that maps pdf's file path to the cache index. I will do a PR soon.

**Comment by atahanacar** [comment]
No, that wouldn't solve any problems and make others worse. Right now, the linked pull request fixes the issue, so we're waiting for it to be merged. For the time being, you can use the previous version I mentioned above, or compile my commit on your own.

As for the capabilities not being used, that's not actually true. Converting the pdf to images as a storage medium would mean text would be rendered at a single resolution with no way to adapt to zooming in. Also, I'm planning on adding/requesting features that actually make use of the pdf just like you said.

**Comment by erik-404err** [comment]
I absolutely love Saber and will use it daily for my studies starting soon. But this issue forces me to disable auto save which definitely bugs be. I would be really grateful if it was fixed soon, considering it's on the top bugs list and is open for quite some time. Unfortunately I'm not able to help in code review or rewrite but here is a PDF which freezes for around 20 seconds.
(since all other mentioned PDFs could not be shared for privacy reasons)
[IPCC_AR6_SYR_SPM.pdf](https://github.com/user-attachments/files/17270308/IPCC_AR6_SYR_SPM.pdf)
Source: https://www.ipcc.ch/report/ar6/syr/summary-for-policymakers/

Thanks for the hard work of all of you :)

**Comment by atahanacar** [comment]
Fixed by 5584b30
