### ISSUE TITLE
Support multiple Nextcloud versions

### ISSUE THREAD

**Issue by s3b3n** [saber-notes/saber#764]
### Motivation

Everytime the supported nextcloud Version changes, the Synchronisation to my managed Nextcloud Server doesnt work anymore until my Hoster updates to the newest Version.

### Solution

Let the enduser selext which nextcloud Version they want to use or add support for multi nextcloud Versions 

### Alternatives

Sync to local folder.

### Saber version

v0.14.0

### Device

- Device: Galaxy Tab S6 Lite
- OS: Android 13

**Comment by ceskyDJ** [comment]
This is a little problematic thing (see https://github.com/provokateurin/nextcloud-neon/issues/391). Saber use Nextcloud Neon, which supports just single Nextcloud version due to Nextcloud API breaking changes between major Nextcloud versions. So, current solution is only changing library for communicating with Nextcloud server. Maybe it's a little relevant to https://github.com/adil192/saber/issues/765 and https://github.com/adil192/saber/issues/201. Unfortunately @adil192 don't want to go throw this way, so only one possible way is here for us - wait for provokateurin (author of Nextcloud Neon) starts to support multiple Nextcloud versions. It should be started sometime between Nextcloud 27 and 28 (see https://github.com/provokateurin/nextcloud-neon/issues/391).

**Comment by adil192** [comment]
Thanks @ceskyDJ, I'll leave this issue open for others to find

**Comment by Iey4iej3** [comment]
For reference, synchronization with a local folder was proposed in https://github.com/adil192/saber/issues/24

**Comment by s3b3n** [comment]
Thanks for explaining

**Comment by strk** [comment]
An alternative would be to allow picking saber version based on nextcloud version. Current stable nextcloud is version 25 but the Saber you get from Android stores requires 27, making it impossible to use with a stable nextcloud deploy

**Comment by ceskyDJ** [comment]
> An alternative would be to allow picking saber version based on nextcloud version. Current stable nextcloud is version 25 but the Saber you get from Android stores requires 27, making it impossible to use with a stable nextcloud deploy

I get the message you want to say. It could be a good idea but e.g. Google Play can't offer more versions of the same app. On the top of that it'd complicate development and maintenance of Saber. It's of course up to @adil192, but I don't like this solution as much.

Btw, I'm on the stable channel and already got Nextcloud 27. So, do you mean production channel or is there something I don't know about versioning?

**Comment by strk** [comment]
I confirm it's the stable branch of nextcloud that's havig 25 as last, unless my install is broken. See attachment


-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ceskyDJ** [comment]
Hmm, interesting. I've set the stable release channel and it brought me Nextcloud 27. Could you try to check your Nextcloud instance? You can use this tool: https://scan.nextcloud.com/.

**Comment by adil192** [comment]
@strk The latest stable is Nextcloud 27. You're probably not getting the update because you your setup doesn't support it (e.g. PHP version too old). Nextcloud updates fall outside of the scope of this project/issue

**Comment by adil192** [comment]
The [nextcloud](https://pub.dev/packages/nextcloud) package currently supports Nextcloud versions 26-28, so I'll mark this as completed
